#![allow(dead_code)]

pub const APP_ID_ENV: &str = "WAYSCRIBER_APP_ID";
pub const PORTAL_APP_ID_ENV: &str = "WAYSCRIBER_PORTAL_APP_ID";
pub const PORTAL_SHORTCUT_ENV: &str = "WAYSCRIBER_PORTAL_SHORTCUT";
pub const PORTAL_SHORTCUT_OPT_IN_ENV: &str = "WAYSCRIBER_ENABLE_PORTAL_SHORTCUTS";

pub const CONFIGURATOR_ENV: &str = "WAYSCRIBER_CONFIGURATOR";
pub const BIN_ENV: &str = "WAYSCRIBER_BIN";
pub const DETACHED_ENV: &str = "WAYSCRIBER_DETACHED";
pub const NO_DETACH_ENV: &str = "WAYSCRIBER_NO_DETACH";
pub const NO_TRAY_ENV: &str = "WAYSCRIBER_NO_TRAY";
pub(crate) const OVERLAY_CHILD_GENERATION_ENV: &str = "WAYSCRIBER_OVERLAY_CHILD_GENERATION";
pub(crate) const DAEMON_WATCHDOG_FD_ENV: &str = "WAYSCRIBER_INTERNAL_DAEMON_WATCHDOG_FD";
pub const CATALOG_HOOKS_TEST_ENV: &str = "WAYSCRIBER_ENABLE_CATALOG_HOOKS_IN_TESTS";
/// Disables the periodic update check regardless of `[updates] check`.
pub const DISABLE_UPDATE_CHECK_ENV: &str = "WAYSCRIBER_DISABLE_UPDATE_CHECK";
pub const FORCE_INLINE_TOOLBARS_ENV: &str = "WAYSCRIBER_FORCE_INLINE_TOOLBARS";
/// Overrides `ui.toolbar.backend` ("auto", "gtk", or "builtin").
pub const TOOLBAR_BACKEND_ENV: &str = "WAYSCRIBER_TOOLBAR_BACKEND";
pub const DEBUG_DAMAGE_ENV: &str = "WAYSCRIBER_DEBUG_DAMAGE";
pub const DEBUG_TOOLBAR_COLOR_ENV: &str = "WAYSCRIBER_DEBUG_TOOLBAR_COLOR";
pub const DEBUG_TOOLBAR_DRAG_ENV: &str = "WAYSCRIBER_DEBUG_TOOLBAR_DRAG";
pub const PERF_LOG_ENV: &str = "WAYSCRIBER_PERF_LOG";
pub const ICON_THEME_PATH_ENV: &str = "WAYSCRIBER_ICON_THEME_PATH";
pub const LOG_FILE_ENV: &str = "WAYSCRIBER_LOG_FILE";
pub const LOG_MAX_SIZE_ENV: &str = "WAYSCRIBER_LOG_MAX_SIZE_MB";
pub const TOOLBAR_DRAG_HANDOFF_MS_ENV: &str = "WAYSCRIBER_TOOLBAR_DRAG_HANDOFF_MS";
pub const TOOLBAR_DRAG_PREVIEW_ENV: &str = "WAYSCRIBER_TOOLBAR_DRAG_PREVIEW";
pub const MAIN_LAYER_ENV: &str = "WAYSCRIBER_MAIN_LAYER";
pub const TOOLBAR_DRAG_THROTTLE_MS_ENV: &str = "WAYSCRIBER_TOOLBAR_DRAG_THROTTLE_MS";
pub const TOOLBAR_POINTER_LOCK_ENV: &str = "WAYSCRIBER_TOOLBAR_POINTER_LOCK";
pub const TRAY_FORCE_PIXMAP_ENV: &str = "WAYSCRIBER_TRAY_FORCE_PIXMAP";
pub const XDG_FULLSCREEN_ENV: &str = "WAYSCRIBER_XDG_FULLSCREEN";
pub const XDG_FULLSCREEN_FORCE_ENV: &str = "WAYSCRIBER_XDG_FULLSCREEN_FORCE";
pub const XDG_OUTPUT_ENV: &str = "WAYSCRIBER_XDG_OUTPUT";

pub const HOME_ENV: &str = "HOME";
pub const HYPRLAND_INSTANCE_SIGNATURE_ENV: &str = "HYPRLAND_INSTANCE_SIGNATURE";
pub const NIRI_SOCKET_ENV: &str = "NIRI_SOCKET";
pub const USERPROFILE_ENV: &str = "USERPROFILE";
pub const PATH_ENV: &str = "PATH";
pub const RUST_LOG_ENV: &str = "RUST_LOG";
pub const SWAYSOCK_ENV: &str = "SWAYSOCK";
pub const WAYLAND_DISPLAY_ENV: &str = "WAYLAND_DISPLAY";
pub const XDG_CURRENT_DESKTOP_ENV: &str = "XDG_CURRENT_DESKTOP";
pub const XDG_SESSION_DESKTOP_ENV: &str = "XDG_SESSION_DESKTOP";
pub const DESKTOP_SESSION_ENV: &str = "DESKTOP_SESSION";
pub const XDG_ACTIVATION_TOKEN_ENV: &str = "XDG_ACTIVATION_TOKEN";
pub const XDG_CACHE_HOME_ENV: &str = "XDG_CACHE_HOME";
pub const XDG_CONFIG_HOME_ENV: &str = "XDG_CONFIG_HOME";
pub const XDG_DATA_HOME_ENV: &str = "XDG_DATA_HOME";
pub const XDG_PICTURES_DIR_ENV: &str = "XDG_PICTURES_DIR";
pub const XDG_RUNTIME_DIR_ENV: &str = "XDG_RUNTIME_DIR";
/// Seat this session belongs to; the input HUD's system capture follows it so
/// a multi-seat machine reads the seat the user is actually sitting at.
pub const XDG_SEAT_ENV: &str = "XDG_SEAT";
pub const DESKTOP_STARTUP_ID_ENV: &str = "DESKTOP_STARTUP_ID";

pub const DESKTOP_ENV_KEYS: [&str; 3] = [
    XDG_CURRENT_DESKTOP_ENV,
    XDG_SESSION_DESKTOP_ENV,
    DESKTOP_SESSION_ENV,
];
